type Query {
  client(id: ID!): Client
  clientDocuments(id: ID!): [Document]
  clientRelatives(id: ID!): [Relative]
}

type Client {
  id: ID!
  name: String!
  age: Int
}

type Document {
  id: ID!
  type: String!
  number: Int!
  issueDate: String
  expiryDate: String
}

type Relative {
  id: ID!
  relationType: String
  name: String!
  age: Int
}
